application: dailygrooves
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /dailygrooves\.js
  script: dailygrooves.app

- url: /cronfetch
  script: dailygrooves.app
  login: admin

- url: /fetch
  script: dailygrooves.app
  login: admin

- url: /fetchworker
  script: dailygrooves.app
  login: admin

- url: /oauth2callback
  script: dailygrooves.app

- url: /(.*\.(gif|png|jpg|css|ico)$)
  static_files: \1
  upload: (.*\.(gif|png|jpg|css|ico)$)

#- url: /(.*)
#  static_files: index.html
#  upload: index.html

libraries:
- name: webapp2
  version: latest
